aws_region = "us-east-1"
sse_algorithm = "AES256" 
profile   = "dev"
role_arn = "arn:aws:iam::317380420770:role/dev-readandwrite"

// cost_center  = "290047"
// business_unit = "BU:SNEUS"
// organization = "Energy Platform"
// standard_ia = "180"
// glacier = "730"
// expiration = "3650" 
// id              = "ne-lj-s3"
// enabled         = true
// prefix          = "whole bucket"


owner	                = "Energy Platform"
organization 	        = "Energy Platform"
scrum_team              = "Engineering"
management_avinstall	= "disable"
project	                = "development"
application_id	        = "337729"
business_unit	        = "BU:SNEUS"
customer                = "Energy Platform"
data_owner              = "Energy Platform"
standard_ia             = "180"
glacier                 = "730"
expiration              = "3650" 
id                      = "ne-lifecycle-s3"
enabled                 = true
prefix                  = "whole bucket"
environment             = "dev"
acl                     = "private" 
